### ISSUE TITLE
English portion of the dataset seems to be corrupted

### ISSUE THREAD

**Issue by pcyin** [google-research-datasets/wiki-atomic-edits#1]
Hi,

I tried to unzip the English portion of the dataset:

```
wget https://storage.googleapis.com/wiki-atomic-edits/english/insertions.tsv.gz
zcat insertions.tsv.gz > insertions.tsv
```

And it gave an error:
```
gzip: insertions.tsv.gz: invalid compressed data--format violated
```

The data files for other languages (e.g., German) seem to be fine.

**Comment by mfaruqui** [comment]
Could you please re download and confirm if the files are looking fine. I have fixed this for English and proceeding to other languages. Thanks for reporting the problem!

**Comment by pcyin** [comment]
It works! Thanks so much!
