### ISSUE TITLE
corpus contents

### ISSUE THREAD

**Issue by BonnieLWebber** [google-research-datasets/wiki-atomic-edits#3]
Manuel/Ellie - In your EMNLP'18 paper (Section 7), the data release indicates that the sentences have been PoS-tagged and dependency parsed, as well as scored w.r.t. a language model.  Has this been done but not included in the corpus distribution, or am I missing where it's located in the insertion and deletion files?

**Comment by mfaruqui** [comment]
Hi Bonnie,

Sorry for the delayed response. We have not yet released the annotated corpus because of some legal issues. We are unsure of how soon that can be done at this stage. We'll keep you posted.

Manaal
