### ISSUE TITLE
Regarding pre-processing tools used

### ISSUE THREAD

**Issue by ajaynagesh** [google-research-datasets/wiki-atomic-edits#4]
Hi Manaal/Ellie, 

Thanks for this dataset! I was wondering if you could throw some more light on the pre-precessing tools used to generate this dataset (you mention [Gillick, 2009](http://u.cs.biu.ac.il/~89-680/gillick2009.pdf), but it looks like that [system is only for English](https://code.google.com/archive/p/splitta/)). Especially for other languages such as Chinese. What was the word segmenter/sentence segmenter used here. 

Thanks! 
Ajay

**Comment by mfaruqui** [comment]
Hi Ajay,

All the tools here were internal Google tools which can unfortunately not be released.

Manaal
